### ISSUE TITLE
Can you provide an installation script for MacOS?

### ISSUE THREAD

**Issue by kamikaze0923** [guicho271828/latplan#3]
Thanks,

**Comment by guicho271828** [comment]
I am planning to change the repository structure. Sorry for the procrastination...

**Comment by guicho271828** [comment]
It is helpful if you can point out where you are stuck, though.

**Comment by guicho271828** [comment]
In fact, because I never had an OSX, I can't replicate your environment. So, a bit of effort from your side is necessary.

**Comment by cyclone923** [comment]
I am on a CentOS linux system now.

I got the following error when running ```make -j 1 -C lisp``` in ```install.sh```.

(py3.7) yangchen@redoubt:/scratch/PycharmProjects/latplan$ make -j 1 -C lisp
make: Entering directory `/scratch/PycharmProjects/latplan/lisp'
LANG=en_US.utf8 ros dynamic-space-size=8000 build domain.ros
WARNING: :SB-EVAL is no longer present in *FEATURES*
compressed 0 bytes into 8 at level -1
compressed 32768 bytes into 256 at level -1
compressed 43679744 bytes into 8718180 at level -1
compressed 2129920 bytes into 595556 at level -1
compressed 13238272 bytes into 4247438 at level -1
mv domain domain.bin
LANG=en_US.utf8 ros dynamic-space-size=8000 build parse-plan.ros
WARNING: :SB-EVAL is no longer present in *FEATURES*
; in: DEFUN MAIN
;     (ITERATE:ITER
;       (ITERATE:FOR ROS.SCRIPT.TO-SAS.3690427216::ACTION
;        ROS.SCRIPT.TO-SAS.3690427216::IN-FILE
;        ROS.SCRIPT.TO-SAS.3690427216::PLANFILE)
;       (ITERATE:COLLECT
;        (TRIVIA.LEVEL2:EMATCH ROS.SCRIPT.TO-SAS.3690427216::ACTION
;          ((LIST #) (MAP 'LIST # #)))))
; 
; caught STYLE-WARNING:
;   Calling #<FUNCTION SYMBOL-NAME> failed, but not by program-error (TYPE-ERROR).
;   Trivia probed candidate function #<FUNCTION SYMBOL-NAME> by calling it with 
;   a single dummy argument 42. The call may fail due to various reasons,
;   but program-error is a strong indication of not being unary.
;    In order to disable this probing, run (SETF *ARITY-CHECK-BY-TEST-CALL* NIL) .
;   
;   Note: This style warning is shown only once.
; 
; compilation unit finished
;   caught 1 STYLE-WARNING condition
compressed 0 bytes into 8 at level -1
compressed 32768 bytes into 256 at level -1
compressed 43384832 bytes into 8653914 at level -1
compressed 2129920 bytes into 591988 at level -1
compressed 13172736 bytes into 4224884 at level -1
mv parse-plan parse-plan.bin
LANG=en_US.utf8 ros dynamic-space-size=8000 build msdd.ros
WARNING: :SB-EVAL is no longer present in *FEATURES*
compressed 0 bytes into 8 at level -1
compressed 32768 bytes into 257 at level -1
compressed 33062912 bytes into 7778975 at level -1
compressed 2228224 bytes into 619989 at level -1
compressed 14680064 bytes into 4719927 at level -1
mv msdd msdd.bin
LANG=en_US.utf8 ros dynamic-space-size=8000 build domain-actionlearner2.ros
WARNING: :SB-EVAL is no longer present in *FEATURES*
Unhandled QUICKLISP-CLIENT:SYSTEM-NOT-FOUND in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                         {10008A8083}>:
  System "dsama" not found

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10008A8083}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<QUICKLISP-CLIENT:SYSTEM-NOT-FOUND {101062E9F3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<QUICKLISP-CLIENT:SYSTEM-NOT-FOUND {101062E9F3}>)
2: (INVOKE-DEBUGGER #<QUICKLISP-CLIENT:SYSTEM-NOT-FOUND {101062E9F3}>)
3: (CERROR "Try again" QUICKLISP-CLIENT:SYSTEM-NOT-FOUND :NAME "dsama")
4: ((LABELS QUICKLISP-CLIENT::RECURSE :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) "dsama")
5: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY) {1010625F6B}>)
6: (QUICKLISP-CLIENT::COMPUTE-LOAD-STRATEGY "dsama")
7: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "dsama" :PROMPT NIL)
8: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unused argument> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1010625C9B}>) [fast-method]
9: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {10072CFC93}> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1010625C9B}>) [fast-method]
10: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) (CL-CSV ITERATE ALEXANDRIA TRIVIA.PPCRE FUNCTION-CACHE SERIALIZABLE-OBJECT DSAMA) :PROMPT NIL :SILENT T :VERBOSE NIL) [fast-method]
11: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {100B22178B}>)
12: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-CLIENT:QUICKLOAD (QUOTE (CL-CSV ITERATE ALEXANDRIA TRIVIA.PPCRE FUNCTION-CACHE SERIALIZABLE-OBJECT DSAMA)) :SILENT T) #<NULL-LEXENV>)
13: (SB-INT:SIMPLE-EVAL-IN-LEXENV (PROGN (ROSWELL:ENSURE-ASDF) (QUICKLISP-CLIENT:QUICKLOAD (QUOTE (CL-CSV ITERATE ALEXANDRIA TRIVIA.PPCRE FUNCTION-CACHE SERIALIZABLE-OBJECT DSAMA)) :SILENT T)) #<NULL-LEXENV>)
14: (EVAL-TLF (PROGN (ROSWELL:ENSURE-ASDF) (QUICKLISP-CLIENT:QUICKLOAD (QUOTE (CL-CSV ITERATE ALEXANDRIA TRIVIA.PPCRE FUNCTION-CACHE SERIALIZABLE-OBJECT DSAMA)) :SILENT T)) NIL NIL)
15: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (PROGN (ROSWELL:ENSURE-ASDF) (QUICKLISP-CLIENT:QUICKLOAD (QUOTE (CL-CSV ITERATE ALEXANDRIA TRIVIA.PPCRE FUNCTION-CACHE SERIALIZABLE-OBJECT DSAMA)) :SILENT T)) NIL)
16: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /scratch/PycharmProjects/latplan/lisp/domain-actionlearner2.ros" {100B1AD413}> #<SB-IMPL::STRING-INPUT-STREAM {100B1AE883}>) {100B1AEC93}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
17: ((FLET SB-FASL::THUNK :IN LOAD))
18: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {7F6AEE7C69AB}> #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /scratch/PycharmProjects/latplan/lisp/domain-actionlearner2.ros" {100B1AD413}> #<SB-IMPL::STRING-INPUT-STREAM {100B1AE883}>) {100B1AEC93}>)
19: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /scratch/PycharmProjects/latplan/lisp/domain-actionlearner2.ros" {100B1AD413}> #<SB-IMPL::STRING-INPUT-STREAM {100B1AE883}>) {100B1AEC93}> NIL)
20: (LOAD #<CONCATENATED-STREAM :STREAMS (#<SB-SYS:FD-STREAM for "file /scratch/PycharmProjects/latplan/lisp/domain-actionlearner2.ros" {100B1AD413}> #<SB-IMPL::STRING-INPUT-STREAM {100B1AE883}>) {100B1AEC93}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
21: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /scratch/PycharmProjects/latplan/lisp/domain-actionlearner2.ros" {100B1AD413}>)
22: (ROSWELL:SCRIPT #P"domain-actionlearner2.ros")
23: (ROS.SCRIPT.DUMP::EXECUTABLE ROSWELL.DUMP.SBCL::SBCL ("domain-actionlearner2.ros"))
24: (ROS.SCRIPT.DUMP::MAIN "executable" "domain-actionlearner2.ros")
25: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE ROS.SCRIPT.DUMP::MAIN) ROSWELL:*ARGV*) #<NULL-LEXENV>)
26: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:QUIT (APPLY (QUOTE ROS.SCRIPT.DUMP::MAIN) ROSWELL:*ARGV*)) #<NULL-LEXENV>)
27: (EVAL-TLF (ROSWELL:QUIT (APPLY (QUOTE ROS.SCRIPT.DUMP::MAIN) ROSWELL:*ARGV*)) NIL NIL)
28: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ROSWELL:QUIT (APPLY (QUOTE ROS.SCRIPT.DUMP::MAIN) ROSWELL:*ARGV*)) NIL)
29: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {10098162C3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
30: ((FLET SB-FASL::THUNK :IN LOAD))
31: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {7F6AEE7C752B}> #<CONCATENATED-STREAM :STREAMS NIL {10098162C3}>)
32: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {10098162C3}> NIL)
33: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {10098162C3}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
34: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /usr/local/etc/roswell/dump.ros" {100980DC03}>)
35: (ROSWELL:SCRIPT "/usr/local/etc/roswell/dump.ros" "executable" "domain-actionlearner2.ros")
36: (ROSWELL:RUN ((:EVAL "(ros:quicklisp)") (:SCRIPT "/usr/local/etc/roswell/dump.ros" "executable" "domain-actionlearner2.ros") (:QUIT NIL)))
37: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:SCRIPT "/usr/local/etc/roswell/dump.ros" "executable" "domain-actionlearner2.ros") (:QUIT NIL)))) #<NULL-LEXENV>)
38: (EVAL (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:SCRIPT "/usr/local/etc/roswell/dump.ros" "executable" "domain-actionlearner2.ros") (:QUIT NIL)))))
39: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/usr/local/etc/roswell/init.lisp\"))") (:EVAL . "(ros:run '((:eval\"(ros:quicklisp)\")(:script \"/usr/local/etc/roswell/dump.ros\"\"executable\"\"domain-actionlearner2.ros\")(:quit ())))")))
40: (SB-IMPL::TOPLEVEL-INIT)
41: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
42: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
43: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
Unhandled UIOP/RUN-PROGRAM:SUBPROCESS-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                         {1000550083}>:
  Subprocess with command "/usr/local/bin/ros  dynamic-space-size=128000 -Q  -L sbcl-bin dump executable domain-actionlearner2.ros"
 exited with error code 1

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1000550083}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {10036D7713}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {10036D7713}>)
2: (INVOKE-DEBUGGER #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {10036D7713}>)
3: (CERROR "IGNORE-ERROR-STATUS" UIOP/RUN-PROGRAM:SUBPROCESS-ERROR :COMMAND "/usr/local/bin/ros  dynamic-space-size=128000 -Q  -L sbcl-bin dump executable domain-actionlearner2.ros" :CODE 1 :PROCESS NIL)
4: (UIOP/RUN-PROGRAM::%CHECK-RESULT 1 :COMMAND "/usr/local/bin/ros  dynamic-space-size=128000 -Q  -L sbcl-bin dump executable domain-actionlearner2.ros" :PROCESS NIL :IGNORE-ERROR-STATUS NIL)
5: (UIOP/RUN-PROGRAM::%USE-SYSTEM "/usr/local/bin/ros  dynamic-space-size=128000 -Q  -L sbcl-bin dump executable domain-actionlearner2.ros" :OUTPUT :INTERACTIVE :ERROR-OUTPUT :INTERACTIVE)
6: (ROSWELL:ROSWELL (" dynamic-space-size=128000 -Q " "-L" "sbcl-bin" "dump" "executable" "domain-actionlearner2.ros") :INTERACTIVE NIL)
7: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE MAIN) ROSWELL:*ARGV*) #<NULL-LEXENV>)
8: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) #<NULL-LEXENV>)
9: (SB-EXT:EVAL-TLF (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL NIL)
10: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL)
11: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {10032B95F3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
12: ((FLET SB-FASL::THUNK :IN LOAD))
13: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {7FF3B69FF53B}> #<CONCATENATED-STREAM :STREAMS NIL {10032B95F3}>)
14: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {10032B95F3}> NIL)
15: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {10032B95F3}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
16: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /usr/local/etc/roswell/build.ros" {10032B8003}>)
17: (ROSWELL:SCRIPT "/usr/local/etc/roswell/build.ros" "domain-actionlearner2.ros")
18: (ROSWELL:RUN ((:SCRIPT "/usr/local/etc/roswell/build.ros" "domain-actionlearner2.ros") (:QUIT NIL)))
19: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:RUN (QUOTE ((:SCRIPT "/usr/local/etc/roswell/build.ros" "domain-actionlearner2.ros") (:QUIT NIL)))) #<NULL-LEXENV>)
20: (EVAL (ROSWELL:RUN (QUOTE ((:SCRIPT "/usr/local/etc/roswell/build.ros" "domain-actionlearner2.ros") (:QUIT NIL)))))
21: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/usr/local/etc/roswell/init.lisp\"))") (:EVAL . "(ros:run '((:script \"/usr/local/etc/roswell/build.ros\"\"domain-actionlearner2.ros\")(:quit ())))")))
22: (SB-IMPL::TOPLEVEL-INIT)
23: ((FLET SB-UNIX::BODY :IN SB-EXT:SAVE-LISP-AND-DIE))
24: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SB-EXT:SAVE-LISP-AND-DIE))
25: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
make: *** [domain-actionlearner2.bin] Error 1
make: Leaving directory `/scratch/PycharmProjects/latplan/lisp'

**Comment by cyclone923** [comment]
Also another error when running setup-dataset.sh.

./setup-dataset.sh: line 15: jbsub: command not found

**Comment by guicho271828** [comment]
> System "dsama" not found

you didnt run install.sh

> jbsub

thats a scheduler we use internally, you should  change it to your job scheduler installed in your cluster. Like Torque/PBS, SGE, LSF etc.

**Comment by guicho271828** [comment]
if you want to run them sequentially just make `$common` an empty string and remove `parallel`.

**Comment by cyclone923** [comment]
```you didnt run install.sh```

I run it line by line by only this line fail.

**Comment by guicho271828** [comment]
Im surprised that you cant handle them yourself... You can just install the dependencies locally if you do not have the admin rights. For example Bison and flex can be downloaded from a GNU website and then put it in the LD Library path. Cmake, make, automake should be available in any reasonable computer cluster / HPC environment. Gnuplot and parallel too. Roswell also uses standard GNU ./configure so you know you can pass options to install it locally.

**Comment by guicho271828** [comment]
closing due to the latest release v5.0.0 .
